In [5]:
import numpy as np
from math import log

# Decision Tree

In [6]:
def Entropy(p):
    res = -p*log(p, 2) - (1-p)*log((1-p), 2)
    return res

In [7]:
Entropy(2/3)

0.9182958340544896

In [8]:
def sumEnt(a, b, m, n):
    p1 = a/(a+b)
    p2 = m/(m+n)
    if a == 0 or b == 0:
        info1 = 0
    else:
        info1 = Entropy(p1)
    if m == 0 or n == 0:
        info2 = 0
    else:
        info2 = Entropy(p2)
    res = (a+b)/(a+b+m+n) *info1 + (m+n)/(a+b+m+n) *info2
    return res, info1, info2

In [9]:
sumEnt(25, 0,  25, 50)

(0.6887218755408672, 0, 0.9182958340544896)

In [10]:
def sumGINI(a, b, m, n):
    p1 = a/(a+b)
    p2 = m/(m+n)

    info1 = 1 - p1 **2 - (1-p1) **2

    info2 = 1 - p2 **2 - (1-p2) **2
    res = (a+b)/(a+b+m+n) *info1 + (m+n)/(a+b+m+n) *info2
    return res, info1, info2

In [11]:
sumGINI(0, 3,  2, 3)

(0.3, 0.0, 0.48)

In [12]:
def C45(a, b, m, n):
    p1 = a/(a+b)
    p2 = m/(m+n)
    if a == 0 or b == 0:
        info1 = 0
    else:
        info1 = Entropy(p1)
    if m == 0 or n == 0:
        info2 = 0
    else:
        info2 = Entropy(p2)
      
    if (a+b) == 0 or (m+n) == 0:
        return 'splitInfo is 0'
    else:
        splitInfo = Entropy((a+b)/(a+b+m+n))
    
    res = (a+b)/(a+b+m+n) *info1 + (m+n)/(a+b+m+n) *info2
    return res, info1, info2

In [13]:
C45(2, 0, 2, 4)

(0.6887218755408672, 0, 0.9182958340544896)

In [14]:
sumGINI(25, 0,  25, 25)

(0.3333333333333333, 0.0, 0.5)

#  Mahalanobis Distance

In [27]:


a = [0.5, 0.5]
b = [0, 1]
e = [[0.3, 0.2], [0.2, 0.3]]


In [28]:
y = np.array(a) - np.array(b)
e = np.array(e)

In [29]:
y.T @ np.linalg.inv(e) @ y

5.000000000000002

# SVD

In [36]:
A = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [37]:
A = np.array(A)
u, s ,vt = np.linalg.svd(A)

In [38]:
print(u)

[[-0.37616823 -0.92655138]
 [-0.92655138  0.37616823]]


In [39]:
print(s)

[14.22740741  1.25732984]


In [40]:
print(vt)

[[-0.35206169 -0.44362578 -0.53518987 -0.62675396]
 [ 0.75898127  0.3212416  -0.11649807 -0.55423774]
 [-0.40008743  0.25463292  0.69099646 -0.54554195]
 [-0.37407225  0.79697056 -0.47172438  0.04882607]]
